export default [
  {
    id: 1,
    title: 'MSK VUE.JS MEETUP #1',
    description:
      'С каждым днем Vue.js становится популярней, все больше разработчиков и компаний делают ставку на данную технологию — 18 июля при поддержке компании Voximplant пройдет митап сообщества MSK VUE.JS, посвященный фреймворку. Спикеры поделятся опытом разработки, участники сообщества обсудят перспективы развития Vue.js.\n\nhttps://voximplant.timepad.ru/event/986750/',
    imageId: 1,
    image: 'https://course-vue.javascript.ru/api/images/1.jpeg',
    date: 1673136000000,
    dateIso: '2023-01-08',
    organizer: 'Игорь Ш.',
    place: 'Москва, офис Voximplant (ул. Мытная 66)',
    organizing: false,
    attending: true,
    agenda: [
      {
        id: 1,
        startsAt: '18:30',
        endsAt: '19:00',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 2,
        startsAt: '19:00',
        endsAt: '19:45',
        type: 'talk',
        title: 'Vue.js 3 — все что ждет нас в будущем',
        description:
          'Скоро нас ждет Vue.js 3. Теперь наш любимый фреймворк станет лучше, быстрее, моднее. Давайте поговорим, что нового нас ждет, что мы получим и что потеряем в результате обновления. Рассмотрим технологии, которыми обогатится Vue.js и которые сделают его, на мой взгляд, самым быстрым и простым фреймворком на рынке.',
        speaker: 'Игорь Шеко — Lead Developer, Voximplant',
        language: 'RU',
      },
      {
        id: 3,
        startsAt: '19:45',
        endsAt: '20:15',
        type: 'coffee',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 4,
        startsAt: '20:15',
        endsAt: '21:00',
        type: 'talk',
        title: 'Опыт использования Vue.js в «Едадиле»',
        description:
          '— Долгая жизнь с Vue: промышленное использования начиная с версии 0.x.\n— Vue внутри webview нативного приложения: подводные камни.\n— Не «стандартный подход» к организации кода и сборке.\n— Авто-оптимизация приложения Vue.\n— Настоящая изоморфность: Vue и другой рантайм.',
        speaker: 'Андрей Кобец — Руководитель отдела разработки фронтенда «Едадила», Яндекс',
        language: 'RU',
      },
      {
        id: 5,
        startsAt: '21:00',
        endsAt: '21:45',
        type: 'talk',
        title: 'Прогрессивные приложения на прогрессивном фреймворке',
        description:
          'PWA (progressive web app, прогрессивное веб-приложение) — один из главных трендов в вебе последние 2 года. Наверняка, вы не раз о нем слышали и даже не раз делали. Или, как я, давно хотели попробовать, но на рабочих проектах в нем не было необходимости. Этот доклад для неслышавших или слышавших, но не пробовавших. Расскажу, что такое PWA, какие технологии подразумевает, в каких браузерах они работают, как интегрировать их во vue-приложение, чем тестировать и какие удобные готовые решения есть можно использовать.',
        speaker: 'Ольга Лесникова — Senior Developer, Voximplant',
        language: 'RU',
      },
      {
        id: 6,
        startsAt: '22:00',
        endsAt: '22:00',
        type: 'closing',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 2,
    title: 'Демо-Митап',
    description:
      'Описание демонстрационного митапа\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    imageId: null,
    image: null,
    date: 1673136000000,
    dateIso: '2023-01-08',
    organizer: 'Demo Organizer',
    place: 'Internet',
    organizing: true,
    attending: false,
    agenda: [
      {
        id: 7,
        startsAt: '09:00',
        endsAt: '10:00',
        type: 'opening',
        title: 'Общий сбор',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 8,
        startsAt: '10:00',
        endsAt: '11:00',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 9,
        startsAt: '11:00',
        endsAt: '12:00',
        type: 'talk',
        title: 'Как делать демо доклады?',
        description: 'Вместо доклада проведём демонстрацию доклада.\nПриходите, будет демонстрационно!',
        speaker: 'Demo, user in Demo Company',
        language: 'RU',
      },
      {
        id: 10,
        startsAt: '12:00',
        endsAt: '12:30',
        type: 'coffee',
        title: 'Перерыв на кофе',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 11,
        startsAt: '12:30',
        endsAt: '13:00',
        type: 'break',
        title: 'Перерыв после кофе',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 12,
        startsAt: '13:00',
        endsAt: '14:00',
        type: 'closing',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 13,
        startsAt: '14:00',
        endsAt: '23:00',
        type: 'afterparty',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 3,
    title: 'Vue.js Moscow Meetup #1',
    description:
      'Ссылка на трансляцию: https://www.youtube.com/watch?v=h9NQs0SEVoA\n\nДрузья привет! Рады сообщить о первом московском митапе, посвященном исключительно фреймоврку Vue.js.\n\nНаша встреча пройдет 22 марта 2018 под покровительством компании Acronis в технопарке - Физтехпарк (г.Москва, Долгопрудненское шоссе, д.3)\nПриглашаются все заинтересованные разработчики от начинающих до опытных.\nФизтехпарк находится за МКАД, но не беспокойтесь, будет организован трансфер от станции метро Алтуфьево и после мероприятия обратно.\nДля желающим приехать на собственном транспорте, проблем с парковкой не будет. Для тех кто все же не сможет до нас добраться, будет организована трансляция выступлений.\n\nhttps://www.meetup.com/ru-RU/vue-js-moscow/events/248462774/',
    imageId: 2,
    image: 'https://course-vue.javascript.ru/api/images/2.jpeg',
    date: 1671667200000,
    dateIso: '2022-12-22',
    organizer: 'Eugeny F.',
    place: 'Москва, Физтехпарк, офис Acronis',
    organizing: false,
    attending: true,
    agenda: [
      {
        id: 28,
        startsAt: '18:30',
        endsAt: '19:00',
        type: 'registration',
        title: 'Сбор и трансфер',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 29,
        startsAt: '19:00',
        endsAt: '19:30',
        type: 'talk',
        title: 'Практика и методы работы со сложными формами во Vue.js',
        description:
          'В докладе на примере от простого к сложному, рассмотрим основные методы и архитектурные подходы работы с редактируемыми пользовательскими данными в современных frontend приложениях.',
        speaker: 'Александр Башкирцев (Software developer, Acronis)',
        language: 'RU',
      },
      {
        id: 30,
        startsAt: '19:30',
        endsAt: '20:00',
        type: 'talk',
        title: 'Внедряем Vue.js в готовый проект, безболезненное избавление от jQuery.',
        description:
          'Что если нам достался в наследство сайт состоящий из неструктурированной, неподдерживаемой лапши из html-css-jquery.... Давайте не будем расстраиваться, а засучим рукава, возьмем в руки vue.js и заставим наше наследство сиять по новому!',
        speaker: 'Alexander Mayorov (CTO, NewHR)',
        language: 'RU',
      },
      {
        id: 31,
        startsAt: '20:00',
        endsAt: '20:10',
        type: 'coffee',
        title: 'Перерыв на кофе и обсуждения',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 32,
        startsAt: '20:10',
        endsAt: '20:40',
        type: 'talk',
        title: 'Простое и понятное управление состоянием во vue.js',
        description:
          'Веб-фреймворки хорошо помогают создавать сложные системы с большим жизненным циклом. Но при решении простых задач современные идеи начинают показывать себя с другой стороны. Разработка компонентов даже с простой бизнес-логикой забирает на себя слишком много времени. Vue хорошо показывает себя в упрощении разработки. Но есть еще места, в которых бывает многовато кода на единицу бизнес-логики. В докладе я расскажу и покажу на примерах как сделать код приложения на Vue еще проще, не потеряв в надежности и выразительности.',
        speaker: 'Александр Сафт (Senior Frontend Developer, Смотрешка)',
        language: 'RU',
      },
      {
        id: 33,
        startsAt: '20:40',
        endsAt: '21:10',
        type: 'talk',
        title: 'Опыт использования Nuxt.js',
        description:
          'Фреймворк Nuxt.js позволяет очень быстро собирать на Vue.js статические сайты. Получающиеся пререндеренные HTML страницы грузятся очень быстро, затем загружают JavaScript код и оживают в ваше приложение. Мы в Voximplant используем Nuxt для внутренних проектов, документации, одностраничных сайтов. В докладе я кратко расскажу про сам фреймворк, его возможности, ограничения, сильные и слабые стороны - и, конечно же, нашу практику его использования',
        speaker: 'Григорий Петров (технический евангелист Voximplant)',
        language: 'RU',
      },
      {
        id: 34,
        startsAt: '21:10',
        endsAt: '23:00',
        type: 'afterparty',
        title: 'Жгучее afterpaty, итальянская пицца, вкусные напитки и продуктивный нетворкинг',
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 4,
    title: 'Vue.js Moscow Meetup #2 - Mail.ru',
    description:
      '!!! Внимание !!!\nРегистрация строго по ссылке:\nhttps://corp.mail.ru/ru/press/events/481/ (Регистрация закрыта)\nВы не сможете попасть на мероприятия, не пройдя регистрацию по ссылке выше.\n\nДрузья привет! Открываем регистрацию на вторую встречу JavaScript/Vue.js разработчиков и всех интересующихся.\nДля тех кто все же не сможет до нас добраться, будет организована трансляция выступлений.\n\nhttps://www.meetup.com/ru-RU/vue-js-moscow/events/251880636/\nСсылка на онлайн трансляцию: https://www.youtube.com/watch?v=SiPKxngecQ0',
    imageId: 3,
    image: 'https://course-vue.javascript.ru/api/images/3.jpeg',
    date: 1672876800000,
    dateIso: '2023-01-05',
    organizer: 'Eugeny F.',
    place: 'Москва, Офис компании Mail.Ru Group',
    organizing: false,
    attending: false,
    agenda: [
      {
        id: 14,
        startsAt: '18:30',
        endsAt: '19:00',
        type: 'registration',
        title: 'Сбор и регистрация',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 15,
        startsAt: '19:00',
        endsAt: '19:30',
        type: 'talk',
        title:
          'Почему Vue.js одинаково хорош для внедрения в legacy код и для построения архитектуры большого приложения с нуля.',
        description:
          'На примерах того как мы в Delivery Club:\n- внедряли vue.js в legacy проект 2009 года.\n- писали приложение на стеке vue + vuex + typescript + rxjs с нуля\n- пишем новый проект на vue.js\nрасскажу и покажу «от простого к сложному», каким может быть vue.js в вашем проекте.',
        speaker: 'Никита Крикун, Frontend Developer, Mail.Ru Group (Delivery Club)',
        language: 'RU',
      },
      {
        id: 16,
        startsAt: '19:30',
        endsAt: '20:00',
        type: 'talk',
        title: 'Сложные анимации во Vue.js',
        description:
          'Анимация состояний и переходов во Vue на примере боевого сайта. От стандартных средств до Timeline-анимации переходов между страницами с помощью сторожевых хуков vue-router и Green Sock.',
        speaker:
          'Сергей Корниенко, Frontend teamlead в Beta Digital Production, преподаватель курса по Vue.js в Moscow Coding School',
        language: 'RU',
      },
      {
        id: 17,
        startsAt: '20:00',
        endsAt: '20:10',
        type: 'coffee',
        title: 'Перерыв на кофе и обсуждения',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 18,
        startsAt: '20:10',
        endsAt: '20:40',
        type: 'talk',
        title: 'Замечательный PWA',
        description:
          'Настало время, когда можно перестать писать код ради кода. Время, когда не надо держать отдельные отделы разработки для написания одних и тех же приложений под разные платформы. PWA – это решение многих проблем кроссплатформенной разработки доступное здесь и сейчас.',
        speaker: 'Владислав Смирнов, Frontend разработчик, Comindware',
        language: 'RU',
      },
      {
        id: 19,
        startsAt: '20:40',
        endsAt: '21:10',
        type: 'talk',
        title: 'Модульно-микросервисная архитектура на на Vue.js',
        description:
          'Мы в ведомостях любим микросервисы. А ещё мы любим Vue.js. В этом докладе я расскажу про опыт объединения микросервисов и вариант реализации модулей в рамках экосистемы Vue.',
        speaker: 'Антон Федоров, Ведущий фронтенд-разработчик, Ведомости',
        language: 'RU',
      },
      {
        id: 20,
        startsAt: '21:10',
        endsAt: '23:00',
        type: 'closing',
        title: 'Завершение; Cбор на afterparty',
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 5,
    title: 'Vue.js Moscow #3 - Ozon',
    description:
      'Друзья привет! Открываем регистрацию на третью встречу JavaScript/Vue.js разработчиков и всех интересующихся. В этот раз мы побываем в гостях у компании Ozon по адресу – “Москва, Пресненская Набережная, 10 блок С, Башня на Набережной”\nДля тех кто все же не сможет до нас добраться, будет организована трансляция выступлений.\nМероприятие бесплатное, но необходима регистрация, количество мест ограничено.\nДо встречи!\n\nhttps://www.meetup.com/ru-RU/vue-js-moscow/events/263421476/',
    imageId: 4,
    image: 'https://course-vue.javascript.ru/api/images/4.jpeg',
    date: 1673481600000,
    dateIso: '2023-01-12',
    organizer: 'Eugeny F.',
    place: 'Москва, Офис компании Mail.Ru Group',
    organizing: false,
    attending: false,
    agenda: [
      {
        id: 21,
        startsAt: '19:00',
        endsAt: '19:30',
        type: 'registration',
        title: 'Сбор и регистрация',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 22,
        startsAt: '19:30',
        endsAt: '20:00',
        type: 'talk',
        title: 'Vue, Typescript и JSX',
        description:
          'Один из существенных недостатков Vue - плохая совместимость с TypeScript из коробки 😅 Я расскажу как победить этот недостаток и начать писать type-safe приложения ✌️!',
        speaker: 'Евгений Петухов, Ozon',
        language: 'RU',
      },
      {
        id: 23,
        startsAt: '20:00',
        endsAt: '20:30',
        type: 'talk',
        title: 'Интеграция и использование Redux во Vue.js',
        description: 'Доклад о варианте интеграции Redux.js во Vue.js, используя Vuex.',
        speaker: 'Анатолий Колесов, Ведущий разработчик, Банк Восточный',
        language: 'RU',
      },
      {
        id: 24,
        startsAt: '20:30',
        endsAt: '20:40',
        type: 'coffee',
        title: 'Перерыв на кофе и обсуждения',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 25,
        startsAt: '20:40',
        endsAt: '21:10',
        type: 'talk',
        title: 'Quasar Framework и SunEngine',
        description:
          'Расскажу про очень функциональный UI и не только UI фреймворк Quasar и продемонстрирую наиболее эффектные его компоненты.\nРасскажу про проект SunEngine и использования Quasar в реальной практике.\n',
        speaker: 'Дмитрий Полянин, lead developer at SunEngine',
        language: 'RU',
      },
      {
        id: 26,
        startsAt: '21:10',
        endsAt: '21:40',
        type: 'talk',
        title: 'Модульно-микросервисная архитектура на на Vue.js',
        description:
          'За последние пару месяцев я просмотрел порядка 20 тестовых заданий для Vue. Все плохо. Основная проблема в том, что люди не умеют (или не хотят) разделять слой представления и слой бизнес-логики в своих приложениях.\n\nЯ расскажу, как, используя простые паттерны и подходы, можно писать большие и сложные приложения. И чтобы их было легко читать, тестировать и менять.',
        speaker: 'Никита Соболев, CTO at wemake.services',
        language: 'RU',
      },
      {
        id: 27,
        startsAt: '21:40',
        endsAt: '23:00',
        type: 'afterparty',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 6,
    title: 'VueConf US',
    description: 'ATX. Code. Vue.\nhttps://vueconf.us/',
    imageId: 5,
    image: 'https://course-vue.javascript.ru/api/images/5.jpeg',
    date: 1673481600000,
    dateIso: '2023-01-12',
    organizer: 'Evan You',
    place: 'USA, AUSTIN CONVENTION CENTER',
    organizing: false,
    attending: false,
    agenda: [
      {
        id: 35,
        startsAt: '07:30',
        endsAt: '09:00',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 36,
        startsAt: '09:00',
        endsAt: '09:30',
        type: 'opening',
        title: 'Opening Keynote with Evan',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 37,
        startsAt: '09:40',
        endsAt: '10:10',
        type: 'talk',
        title: 'Get the most out of Vue Router',
        description:
          "Routers in Single page applications touch a broad part of our business logic. As a consequence, we often end up with different ways of handling the same pattern/UX/logic in our code and we often wonder which one is better and why. Different ways of handling data fetching that change the user experience, different ways to implement layouts, and many more. During this talk, I will cover very practical implementations that I have found useful in the past and explain the differences between various Vue Router features. After the talk you will have a better understanding of Vue Router's API and hopefully the excitement to refactor some bits of your Vue app!",
        speaker: 'Eduardo',
        language: 'EN',
      },
      {
        id: 38,
        startsAt: '10:10',
        endsAt: '09:30',
        type: 'break',
        title: 'Break 1.0',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 39,
        startsAt: '10:40',
        endsAt: '11:10',
        type: 'talk',
        title: 'All you need is <s>love</s> Apollo Client',
        description:
          'While we usually mention Apollo Client only in connection with GraphQL, it can do a lot more things to your Vue application such as accessing REST endpoints and replacing Vuex in managing application state! In this talk, I will cover these advanced cases while also explaining the basics of using Apollo with GraphQL endpoints',
        speaker: 'Natalia Tepluhina',
        language: 'EN',
      },
      {
        id: 40,
        startsAt: '11:10',
        endsAt: '11:40',
        type: 'talk',
        title: 'The State of CSS in Vue',
        description:
          "There are a lot of ways to include CSS in your Vue apps, and they all have pros and cons. Knowing which method to choose can be confusing with all the different options available. In this talk, you'll learn about different ways to bring CSS into your Vue app and how to pick a methodology for your project.",
        speaker: 'Jamena McInteer',
        language: 'EN',
      },
      {
        id: 41,
        startsAt: '11:40',
        endsAt: '12:10',
        type: 'talk',
        title: "What you'll love in Vue 3",
        description: "What you'll love in Vue 3",
        speaker: 'Alex Kyriakidis',
        language: 'EN',
      },
      {
        id: 42,
        startsAt: '12:10',
        endsAt: '13:10',
        type: 'coffee',
        title: 'Lunch 1.0',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 43,
        startsAt: '13:10',
        endsAt: '14:10',
        type: 'other',
        title: 'Lightning Talks 1.0',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 44,
        startsAt: '14:10',
        endsAt: '14:40',
        type: 'break',
        title: 'Break 1.1',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 45,
        startsAt: '14:40',
        endsAt: '15:10',
        type: 'talk',
        title: 'Vuetify v2+',
        description:
          'A review of the past year of Vuetify, the v2 releases and upcoming features in v2.2. Details of new packages for the Vuetify ecosystem and future projects on the horizon.',
        speaker: 'John Leider',
        language: 'EN',
      },
      {
        id: 46,
        startsAt: '15:10',
        endsAt: '15:40',
        type: 'talk',
        title: "Content Loading That Isn't Broken",
        description:
          "How does Vue.js handle rerouting and loading new content with a screen reader? Let's explore how we can improve the experience for a lot of users who rely on assistive technologies.",
        speaker: 'Maria Lamardo',
        language: 'EN',
      },
      {
        id: 47,
        startsAt: '15:40',
        endsAt: '16:10',
        type: 'talk',
        title: 'Documenting components made easy',
        description:
          "Using shared components without proper documentation can be a pain. Whether you're publishing a component library, or just sharing components with your colleagues, increase the ease of adoption by writing clear documentation. In this talk, I'll show you how easy it is to write beautiful documentation for your components which other developers will love.",
        speaker: 'Bart Ledoux',
        language: 'EN',
      },
      {
        id: 48,
        startsAt: '16:10',
        endsAt: '16:40',
        type: 'break',
        title: 'Break 1.3',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 49,
        startsAt: '16:40',
        endsAt: '17:10',
        type: 'talk',
        title: 'TypeScript & Vue @ Politico',
        description:
          '“JavaScript that scales” is the tagline for TypeScript, and it can be a beautiful partner for increasingly complex Vue apps. We’ll discuss how CLI TypeScript Vue projects can increase development speed, decrease onboarding time, type errors, and typos, while encouraging self-documenting & maintainable code. Finally, let’s look at remaining hurdles for Vue’s TS implementation (Vuex, mixins, templates), and how the composition API + Vetur will continue to ease those growing pains.',
        speaker: 'Jack Koppa',
        language: 'EN',
      },
      {
        id: 50,
        startsAt: '17:10',
        endsAt: '17:40',
        type: 'talk',
        title: 'Unconventional Vue—Vue as a Backend Framework',
        description:
          'While Vue has emerged as a dominant frontend framework, we can’t forget about the other side of the spectrum. What if we leveraged Vue 3.0’s powerful standalone observability system to manage our backend datastore, with all its reactivity goodness? We could build a highly reactive chat app, power a live scoreboard, or maybe even have Vue trigger AWS Lambda functions as app data changes…',
        speaker: 'Oscar Spencer',
        language: 'EN',
      },
      {
        id: 51,
        startsAt: '18:15',
        endsAt: '19:45',
        type: 'afterparty',
        title: 'Conference Reception: Austin SPEAKEASY, 412 Congress Ave. Drinks and light snacks.',
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 7,
    title: 'Vue 3 Course',
    description: 'Курс по Vue 3',
    imageId: null,
    image: null,
    date: 1676419200000,
    dateIso: '2023-02-15',
    organizer: 'Grigorii K. Shartsev',
    place: 'learn.javascript.ru',
    organizing: false,
    attending: true,
    agenda: [],
  },
];
